#
# To edit the config variables of the containers
# check the file: .env
#

version: '2'
services:
  db:
    image: postgres:9.5
    env_file:
      - ./.env
    volumes:
      - './create_database.sql:/create_database.sql'
    ports:
      - "5432"

  web:
    env_file:
      - ./.env
    image: event-rest-service:0.1.0
    ports:
      - '9000:9000'
    links:
      - db